
package order;

import java.io.BufferedOutputStream;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardOpenOption.APPEND;
import static java.nio.file.StandardOpenOption.CREATE;

/**
 *
 * @author Michelle
 */
public class OrderForm extends javax.swing.JFrame {

    private static String promptForName() {
        String userName = JOptionPane.showInputDialog("Please Enter Your Full Name.");
       
       if (userName.length() <=1) {
          return null; 
       } else {
         return userName;
       }
    }
     private static void promptUser() {
        String userName = promptForName();
        
         //Adds multiple text fields to a JOptionPane
        JTextField name = new JTextField();
        JTextField streetAddress = new JTextField();
        JTextField city = new JTextField();
        JTextField state = new JTextField();
        JTextField zip = new JTextField();
        JTextField phone = new JTextField();
        
         
       
        //Create array of objects to fill the JTextFields created above
        Object[] fields = {
            
           //Displayed text + empty field to take user input
           "Name", name,
           "Street Address", streetAddress,
           "City", city,
           "State", state,
           "Zip", zip,
           "Phone", phone
                
        };
        
      try {  
        do {
                
               
            if (userName == null || userName.trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Cannot Be Left Blank", "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showInputDialog("Please Enter Your Full Name.");
            }
            else {
                 JOptionPane.showConfirmDialog(null, fields, "Please Enter Your Information", JOptionPane.OK_CANCEL_OPTION);
                 
                 //creates new variables from the above fields 
                  String cn = name.getText();
                  String sa = streetAddress.getText();
                  String ci = city.getText();
                  String st = state.getText();
                  String z = zip.getText();
                  String ph = phone.getText();
                  
                  //and converts to bytes
                  byte data1[] = cn.getBytes();
                  byte data2[] = sa.getBytes();
                  byte data3[] = ci.getBytes();
                  byte data4[] = st.getBytes();
                  byte data5[] = z.getBytes();
                  byte data6[] = ph.getBytes();
                  
            //creates the text file
            Path p = Paths.get("SubOrder.text");
        try  (OutputStream out = new BufferedOutputStream(Files.newOutputStream(p, CREATE, APPEND))) {
            
            //reads the user's input from each data variable above and writes to the text file
            out.write(data1, 0, data1.length );
            out.write(System.getProperty("line.separator").getBytes());
            out.write(data2, 0, data2.length);
            out.write(System.getProperty("line.separator").getBytes());
            out.write(data3, 0, data3.length);
            out.write(System.getProperty("line.separator").getBytes());
            out.write(data4, 0, data4.length);
            out.write(System.getProperty("line.separator").getBytes());
            out.write(data5, 0, data5.length);
            out.write(System.getProperty("line.separator").getBytes());
            out.write(data6, 0, data6.length);
            out.write(System.getProperty("line.separator").getBytes());
              
        }catch  (IOException exp) {
            System.err.println(exp);
        }      
                 JOptionPane.showMessageDialog(null,"Welcome to the Sub Shop " + userName + "!"); 
            }
            
            
        
 } while (userName.trim().isEmpty()&& userName == null);
      }catch (NullPointerException e){
          
          JOptionPane.showConfirmDialog(null, fields, "Please Enter Your Information", JOptionPane.OK_CANCEL_OPTION);
          
          JOptionPane.showMessageDialog(null,"Welcome to the Sub Shop, " + userName + "!"); 
          
      } 
      
    }

    @SuppressWarnings("empty-statement")
    public OrderForm() {//initializes form
        initComponents();
  
                }
        
  
     //all code highlighted in grey is autogenerated by swing   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displaySelected = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        sandType = new javax.swing.JComboBox<>();
        breadType = new javax.swing.JComboBox<>();
        breadSize = new javax.swing.JComboBox<>();
        sideItem = new javax.swing.JComboBox<>();
        drink = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblSand = new javax.swing.JLabel();
        lblBread = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblSide = new javax.swing.JLabel();
        lblDrink = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 0), new java.awt.Color(0, 204, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 204, 0)));

        displaySelected.setBackground(new java.awt.Color(204, 255, 204));
        displaySelected.setColumns(20);
        displaySelected.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        displaySelected.setLineWrap(true);
        displaySelected.setRows(5);
        displaySelected.setFocusable(false);
        jScrollPane1.setViewportView(displaySelected);

        btnSubmit.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmit.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        btnSubmit.setLabel("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        sandType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Italian", "BLT", "Club", "Ham & Swiss", "Veggie" }));
        sandType.setName(""); // NOI18N
        sandType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandTypeActionPerformed(evt);
            }
        });

        breadType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "White", "Wheat", "Rye", "Gluten Free" }));
        breadType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadTypeActionPerformed(evt);
            }
        });

        breadSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "4 inch", "6 inch", "8 inch", "12 inch" }));
        breadSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadSizeActionPerformed(evt);
            }
        });

        sideItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Chips", "Fruit Cup", "Potato Salad", "Pasta Salad" }));
        sideItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideItemActionPerformed(evt);
            }
        });

        drink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Pepsi", "Sierra Mist", "Dr. Pepper", "Gingerale", "Rootbeer", "Sweet Tea", "Unsweet Tea", "Bottled Water" }));
        drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Sub Shop");

        lblSand.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        lblSand.setText("Sandwich");

        lblBread.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        lblBread.setText("Bread");

        lblSize.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        lblSize.setText("Size");

        lblSide.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        lblSide.setText("Side");

        lblDrink.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        lblDrink.setText("Drink");

        btnCancel.setBackground(new java.awt.Color(204, 255, 204));
        btnCancel.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblSand)
                        .addGap(70, 70, 70)
                        .addComponent(lblBread)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(sandType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(breadType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnCancel)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSubmit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(breadSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSize)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sideItem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(drink, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblSide)
                                .addGap(59, 59, 59)
                                .addComponent(lblDrink)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSand)
                    .addComponent(lblBread)
                    .addComponent(lblDrink)
                    .addComponent(lblSide)
                    .addComponent(lblSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sandType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(breadType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(breadSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sideItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(btnCancel))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Displays a Thank you message when the "Submit" button is pressed
        JOptionPane.showMessageDialog(null, "Your Order has been submitted!" + "\n" +  "Thank you for your business!", "Order Processed", JOptionPane.INFORMATION_MESSAGE);
        
        //creates new variable from the JTextArea displaySelected
         String uS = displaySelected.getText();
         //converts it to bytes
            byte data[] = uS.getBytes();
            //creates text file
            Path p = Paths.get("SubOrder.text");
            
            //reads user sandwich selections from JTextArea and outputs to the file
        try  (OutputStream out = new BufferedOutputStream(Files.newOutputStream(p,CREATE, APPEND))) {
            out.write(data, 0, data.length);
            out.write(System.getProperty("line.separator").getBytes());
              
        }catch  (IOException exp) {
            System.err.println(exp);
        }
        
        
        System.exit(0);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void sandTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandTypeActionPerformed
        // displays sandwich select in text window
     displaySelected.setText(sandType.getSelectedItem().toString()+"\r\n");
    }//GEN-LAST:event_sandTypeActionPerformed

    private void breadTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadTypeActionPerformed
        // displays bread selection in text window
        displaySelected.append(breadType.getSelectedItem().toString()+"\r\n");
    }//GEN-LAST:event_breadTypeActionPerformed

    private void breadSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadSizeActionPerformed
        // displays bread size selected in text window
        displaySelected.append(breadSize.getSelectedItem().toString()+"\r\n");
    }//GEN-LAST:event_breadSizeActionPerformed

    private void sideItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideItemActionPerformed
        // displays side item selected in text window
        displaySelected.append(sideItem.getSelectedItem().toString()+"\r\n");
    }//GEN-LAST:event_sideItemActionPerformed

    private void drinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkActionPerformed
        // displays drink choice in text window
        displaySelected.append(drink.getSelectedItem().toString()+"\r\n");
    }//GEN-LAST:event_drinkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Cancels the order and closes app
        JOptionPane.showMessageDialog(null, "Your Order has been Cancelled");
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        promptUser();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
       
    }
    
    
   
//below code is all auto-generated
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> breadSize;
    private javax.swing.JComboBox<String> breadType;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextArea displaySelected;
    private javax.swing.JComboBox<String> drink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBread;
    private javax.swing.JLabel lblDrink;
    private javax.swing.JLabel lblSand;
    private javax.swing.JLabel lblSide;
    private javax.swing.JLabel lblSize;
    private javax.swing.JComboBox<String> sandType;
    private javax.swing.JComboBox<String> sideItem;
    // End of variables declaration//GEN-END:variables
}
